kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: Cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 3000 #Grafana
        hostPort: 3000
        protocol: TCP
      - containerPort: 9090  # Prometheus
        hostPort: 9090
        protocol: TCP
      - containerPort: 8080  # Jenkins/Jolokia
        hostPort: 8080
        protocol: TCP
  - role: worker
  - role: worker
