apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'jolokia'
        metrics_path: '/jolokia/read/java.lang:type=Memory/HeapMemoryUsage'
        static_configs:
          - targets: ['jenkins-tomcat-jolokia:8080']
